nao_dcm/gazebo_ros_control/pid_gains:
  HeadYaw: {p: 1000.0, i: 0.0, d: 0.0}

  HeadPitch: {p: 1000.0, i: 0.0, d: 0.0}

  LShoulderPitch: {p: 5000.0, i: 0.0, d: 0.0}

  LElbowYaw: {p: 100.0, i: 0.0, d: 0.0}

  LElbowRoll: {p: 100.0, i: 0.0, d: 0.0}

  LShoulderRoll: {p: 5000.0, i: 0.0, d: 0.0}

  LWristYaw: {p: 20.0, i: 0.0, d: 0.0}

  LHand: {p: 1.0, i: 0.0, d: 0.0}

  RShoulderPitch: {p: 5000.0, i: 0.0, d: 0.0}

  RElbowYaw: {p: 100.0, i: 0.0, d: 0.0}

  RElbowRoll: {p: 100.0, i: 0.0, d: 0.0}

  RShoulderRoll: {p: 5000.0, i: 0.0, d: 0.0}

  RWristYaw: {p: 20.0, i: 0.0, d: 0.0}

  RHand: {p: 1.0, i: 0.0, d: 0.0}

  LHipYawPitch: {p: 1000.0, i: 0.0, d: 0.0}

  LHipRoll: {p: 1000.0, i: 0.0, d: 0.0}

  LHipPitch: {p: 1000.0, i: 0.0, d: 0.0}

  LKneePitch: {p: 1000.0, i: 0.0, d: 0.0}

  LAnklePitch: {p: 1000.0, i: 0.0, d: 0.0}

  LAnkleRoll: {p: 1000.0, i: 0.0, d: 0.0}

  RHipYawPitch: {p: 1000.0, i: 0.0, d: 0.0}

  RHipRoll: {p: 1000.0, i: 0.0, d: 0.0}

  RHipPitch: {p: 1000.0, i: 0.0, d: 0.0}

  RKneePitch: {p: 1000.0, i: 0.0, d: 0.0}

  RAnklePitch: {p: 1000.0, i: 0.0, d: 0.0}

  RAnkleRoll: {p: 1000.0, i: 0.0, d: 0.0}