# DO NOT CHANGE IT
Version: V4

# Choose what components are enabled on startup
SonarEnabled: true
TactilesEnabled: true
BumpersEnabled: true
FootContactsEnabled: true

# Camera related parameters
UseCamera: true
TopCameraEnabled: true
BottomCameraEnabled: true

# Application related parameters
PublishIMU: true

# ROS related paramaters
TopicQueue: 10

# Robot-Connection related parameters
RobotPort: 9559
RobotIP: nao.local
DriverBrokerPort: 54000
DriverBrokerIP: 0.0.0.0
CameraBrokerPort: 54001
CameraBrokerIP: 0.0.0.0

# Communication related parameters
HighCommunicationFrequency: 25
LowCommunicationFrequency: 10
ControllerFrequency: 10
CameraFrequency: 15

# DO NOT CHANGE IT
Prefix: nao_dcm
